# Generated by Django 5.1.4 on 2025-01-12 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBConsignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingIdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.TextField()),
                ('activity_status', models.BooleanField(default=False)),
                ('tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBConsignment.trackingid')),
            ],
        ),
    ]
