# Generated by Django 5.1.4 on 2025-01-20 22:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBConsignment', '0002_trackingidhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('message', models.TextField()),
                ('company', models.CharField(default='GlobeGoExpress', max_length=255)),
                ('country', models.CharField(default='Japan', max_length=255)),
                ('postal_code', models.CharField(default='232323', max_length=255)),
                ('vat', models.CharField(default='MIT', max_length=255)),
                ('phone', models.CharField(default='+1234567890', max_length=255)),
                ('city', models.CharField(default='New Jersey', max_length=255)),
                ('terms', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('secreteQuestion', models.TextField()),
                ('secreteAnswer', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('company', models.CharField(default='GlobeGoExpress', max_length=255)),
                ('country', models.CharField(default='Japan', max_length=255)),
                ('postal_code', models.CharField(default='232323', max_length=255)),
                ('province', models.CharField(default='MIT', max_length=255)),
                ('phone', models.CharField(default='+1234567890', max_length=255)),
                ('city', models.CharField(default='New Jersey', max_length=255)),
                ('terms', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
