# Generated by Django 5.1.4 on 2025-01-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBConsignment', '0003_businessaccount_consignmentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignmentuser',
            name='user',
        ),
    ]
