# Generated by Django 5.1.4 on 2025-01-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBConsignment', '0005_remove_businessaccount_user_consignmentuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='email',
            field=models.EmailField(default='admin@globegoexpress.com', max_length=255),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='first_name',
            field=models.CharField(default='GlobeGoExpress', max_length=255),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='last_name',
            field=models.CharField(default='GlobeGoExpress', max_length=255),
        ),
    ]
