# Generated by Django 5.1.1 on 2024-10-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='tenant',
        ),
    ]
