# Generated by Django 5.1.1 on 2024-10-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0002_remove_applicationuseraccount_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuseraccount',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.tenant'),
        ),
    ]
