# Generated by Django 5.1.1 on 2024-10-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0003_applicationuseraccount_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuseraccount',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
