# Generated by Django 5.1.1 on 2024-11-27 00:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_applicationuseraccount_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuseraccount',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicationuseraccount',
            name='last_login_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
