# Generated by Django 5.1.4 on 2024-12-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0010_remove_applicationuseraccount_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='is_first_time',
        ),
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='is_root_account',
        ),
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='is_tenant_admin',
        ),
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='applicationuseraccount',
            name='mobile_number',
        ),
    ]
