# Generated by Django 5.1.4 on 2024-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thane Rivers', max_length=32)),
                ('photo', models.CharField(default='http://google.com', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
