# Generated by Django 5.1.4 on 2024-12-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritymanagement', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='balance',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='promocode',
            name='cost',
            field=models.IntegerField(default=199),
        ),
    ]
