# Generated by Django 5.1.4 on 2024-12-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritymanagement', '0004_promocode_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(default='FGSHWEQO', max_length=8, unique=True),
        ),
    ]
