# Generated by Django 5.1.4 on 2024-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebritymanagement', '0007_alter_promocode_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thane Rivers', max_length=64)),
                ('email', models.CharField(default='http://google.com', max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
